### ISSUE TITLE
How to train the xvector extractor with own data

### ISSUE THREAD

**Issue by llior** [BUTSpeechFIT/VBx#39] opened 2021-12-28 11:23 UTC
Hello，
I tried to use [VBx-training-recipe](https://github.com/phonexiaresearch/VBx-training-recipe.git) to train resnet101 xvector extractor with cnceleb1 and cnceleb2. After 210 epochs training, I replaced the raw_75.pth, but got bad result. I found that the fbank of  VBx-training-recipe was extracted by kaldi, that of VBx was extracted by  features.py. 
What I'm not sure whether it is right to use VBx-training-recipe directly to trian xvector extractor. How do I train the xvector extractor with own data？

**Comment by fnlandini** [comment] 2022-01-04 12:08
Hi @llior, 
It is true that the features in the two repositories are not the same but the recipes are like that and all the results we reported are following that setup so there is nothing strange there. 
I understand that you used VBx-training-recipe to train the extractor (which is correct) but I have a question.
Did you run the training using the exact same training data as we did (namely VoxCeleb 1 and 2 and CN-CELEB 1)? This would be a good way of validating that everything in your training is correct. Then, by replacing the training data (using CN-CELEB 1 and 2 instead), you should be able to see the impact of that change.

Also, note that VoxCeleb 1 and 2 account for more than 7000 speakers while CN-CELEB 2 has 2000 and probably also less amount of hours of speech (sorry, I do not know the details about CN-CELEB 2). This can have a big impact and make the x-vector extractor worse. Moreover, I do not know the details about channel characteristics and that could also play a role in the extractor quality.

If you could show an example of what you mean by "bad result" (i.e. DER results), I could perhaps have a better idea if the difference is due to a completely faulty training or if maybe the model is simply worse because of lesser amount of training data in the x-vector extractor.

**Comment by llior** [comment] 2022-01-04 12:39
Thanks a lot for your answer! After parameter fine-tuning on development data, it works now. When I use pretrained resnet101 model(raw_75.pt), the DER is 15.30% on our corpus. By comparison, the DER is 15.55% on the same diarization corpus when we use resnet101 model that is only trained with CN-celeb1 and CN-celeb2.

**Comment by fnlandini** [comment] 2022-01-04 12:43
That does not look bad! I guess either CN-CELEBs are a better match for your data (in spite of less training data) or maybe you could also do fine-tuning with the pretrained model (in case you have not) to improve the 15.3
Sorry for the delay to reply, you caught me on holidays last week. If you think the problem is solved, feel free to close this issue.

**Closed as completed** 2022-01-04 12:53 UTC
